# Generated by Django 5.2.6 on 2025-09-30 02:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('ubicacion', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('duracion_min', models.PositiveSmallIntegerField(default=60)),
                ('capacidad', models.PositiveIntegerField()),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=12, unique=True)),
                ('marca', models.CharField(blank=True, max_length=50, null=True)),
                ('modelo', models.CharField(blank=True, max_length=50, null=True)),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('bus', 'bus'), ('van', 'van')], default='van', max_length=10)),
                ('capacidad', models.PositiveSmallIntegerField()),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=255)),
                ('vigente', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_blacklist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_colab', models.CharField(choices=[('guia', 'guia'), ('chofer', 'chofer')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'admin'), ('colaborador', 'colaborador'), ('cliente', 'cliente')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('fecha_nac', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('estado', models.CharField(choices=[('pending_admin', 'Pendiente admin'), ('admin_rejected', 'Rechazada por admin'), ('pending_client', 'Pendiente confirmación cliente'), ('confirmed', 'Confirmada'), ('cancelled', 'Cancelada')], default='pending_admin', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('token_confirmacion', models.CharField(blank=True, max_length=64, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='api.evento')),
            ],
        ),
        migrations.CreateModel(
            name='InvitadoReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_invitado', models.CharField(blank=True, max_length=12, null=True)),
                ('nombre_invitado', models.CharField(max_length=100)),
                ('edad_invitado', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitados', to='api.reserva')),
            ],
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_chofer', to='api.colaborador')),
                ('guia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones_guia', to='api.colaborador')),
                ('evento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asignacion', to='api.evento')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.vehiculo')),
            ],
        ),
    ]
