# Generated by Django 5.2.6 on 2025-10-01 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='reserved_count',
        ),
        migrations.AlterField(
            model_name='evento',
            name='capacidad',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='token_confirmacion',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['cliente', 'vigente'], name='api_blackli_cliente_c9b54d_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['fecha'], name='api_evento_fecha_41f7c0_idx'),
        ),
        migrations.AddIndex(
            model_name='evento',
            index=models.Index(fields=['activo'], name='api_evento_activo_c9db73_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['cliente', 'estado'], name='api_reserva_cliente_1abf89_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['evento', 'estado'], name='api_reserva_evento__b36520_idx'),
        ),
        migrations.AddIndex(
            model_name='reserva',
            index=models.Index(fields=['-fecha_creacion'], name='api_reserva_fecha_c_cb1bf7_idx'),
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gt', 0)), name='reserva_cantidad_gt_0'),
        ),
    ]
